# Generated by Django 5.0.1 on 2024-02-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vlogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='fname')),
                ('last_name', models.CharField(max_length=50, verbose_name='lname')),
                ('Date', models.DateField(verbose_name='table_date')),
                ('img', models.ImageField(upload_to=None, verbose_name='img')),
                ('email', models.EmailField(max_length=254, verbose_name='table_email')),
                ('thought', models.TextField(verbose_name='thought')),
            ],
        ),
    ]
