# Generated by Django 5.0.1 on 2024-02-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlogdetails',
            name='img',
            field=models.ImageField(upload_to='img/', verbose_name='img'),
        ),
    ]
